image:
  file: .gitpod.Dockerfile

ports:
  - port: 44232
    onOpen: open-browser

tasks:
  - init: |
      yarn install;
      yarn run build;
      ./dev docker-build;
      ./dev docker-composer-install;
      ./dev docker-up;
