version: '3.7'

services:
  utility:
    env_file:
      - .env
      - .env.local
    image: ubuntu:18.04
    restart: always
    container_name: stmark-utility
    volumes:
      - .:/opt/project
      - cp-resources-volume:/cp-resources-volume
      - image-cache-volume:/image-cache-volume
      - files-volume:/files-volume
      - files-above-webroot-volume:/files-above-webroot-volume
      - log-volume:/log-volume
      - public-cache-volume:/public-cache-volume
      - storage-volume:/storage-volume
      - uploads-volume:/uploads-volume
    command: bash -c "chmod +x /opt/project/docker/utility/prod.sh && /opt/project/docker/utility/prod.sh"

  app:
    restart: always
    volumes:
      - cp-resources-volume:/opt/project/public/cpresources
      - image-cache-volume:/opt/project/public/imagecache
      - files-volume:/opt/project/public/files
      - files-above-webroot-volume:/opt/project/filesAboveWebroot
      - log-volume:/var/log
      - public-cache-volume:/opt/project/public/cache
      - storage-volume:/opt/project/storage
      - uploads-volume:/opt/project/public/uploads
      - nginx-master_certbot-conf-volume:/etc/letsencrypt
    networks:
      default:
        aliases:
          - stmarkreformed.com
          - www.stmarkreformed.com

  db:
    restart: always
    volumes:
      - log-volume:/var/log

volumes:
  cp-resources-volume:
  image-cache-volume:
  files-volume:
  files-above-webroot-volume:
  public-cache-volume:
  uploads-volume:
