version: '3.7'

services:
  web:
    env_file: .env
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    container_name: stmark-web
    ports:
      - 44232:44232
    environment:
      HOSTNAME: stmark-web
    networks:
      default:
        aliases:
          - stmarkreformed.com
          - www.stmarkreformed.com
          - staging.stmarkreformed.com
          - stmarkreformed.localtest.me

  php:
    env_file: .env
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: stmark-php
    environment:
      HOSTNAME: stmark-php
    networks:
      default:
        aliases:
          - stmark-php

  db:
    env_file: .env
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    container_name: stmark-db
    environment:
      HOSTNAME: stmark-db
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - 44230:3306
    networks:
      default:
        aliases:
          - stmark-db

volumes:
  db-volume:

networks:
  default:
    external:
      name: proxy
