version: '3'

services:
  utility:
    image: buzzingpixel/utility:latest
    container_name: utility-stmarkreformed
    environment:
      HOSTNAME: utility-stmarkreformed
    volumes:
      - .:/app:delegated
      - ./dev/null:/app/.git:delegated
      - ./dev/null:/app/.idea:delegated
      - cache-data:/cache-volume
      - vendor-data:/vendor-volume
      - db-data:/db-volume
      - public-cache:/public-cache-volume
      - cpresources:/cpresources-volume
      - imagecache:/imagecache-volume
    command: bash -c "chmod +x /app/scripts/devUtilityScript.sh && /app/scripts/devUtilityScript.sh"
    networks:
      common:
  web:
    image: buzzingpixel/nginx:latest
    container_name: nginx-stmarkreformed
    environment:
      HOSTNAME: nginx-stmarkreformed
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ${DOCKER_RSA_FILE}:/tmp/.ssh/id_rsa:delegated
      - ${DOCKER_RSA_PUB_FILE}:/tmp/.ssh/id_rsa.pub:delegated
      - ${DOCKER_NGINX_CONF_FILE}:/etc/nginx/conf.d/site.conf:delegated
      - .:/app:delegated
      - ./dev/null:/app/.git:delegated
      - ./dev/null:/app/.idea:delegated
      - ./dev/null:/app/node_modules:delegated
      - vendor-data:/app/vendor
      - cache-data:/app/storage
      - public-cache:/app/public/cache
      - cpresources:/app/public/cpresources
      - imagecache:/app/public/imagecache
    networks:
      common:
        aliases:
          - ${SERVER_NAME_ALIAS}
  php:
    image: buzzingpixel/php7.2:latest
    container_name: php-stmarkreformed
    environment:
      HOSTNAME: php-stmarkreformed
    volumes:
      - ${DOCKER_RSA_FILE}:/tmp/.ssh/id_rsa:delegated
      - ${DOCKER_RSA_PUB_FILE}:/tmp/.ssh/id_rsa.pub:delegated
      - ./serverConfig/php/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini:delegated
      - ${DOCKER_PHP_ENV_INI_FILE}:/usr/local/etc/php/conf.d/php-env-config.ini:delegated
      - ./serverConfig/php/fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf
      - .:/app:delegated
      - ./dev/null:/app/.git:delegated
      - ./dev/null:/app/.idea:delegated
      - ./dev/null:/app/node_modules:delegated
      - vendor-data:/app/vendor
      - cache-data:/app/storage
      - public-cache:/app/public/cache
      - cpresources:/app/public/cpresources
      - imagecache:/app/public/imagecache
    networks:
      common:
  db:
    image: buzzingpixel/mariadb:latest
    container_name: db-stmarkreformed
    restart: always
    environment:
      HOSTNAME: db-stmarkreformed
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    user: "1000:50"
    volumes:
      - ${DOCKER_RSA_FILE}:/tmp/.ssh/id_rsa:delegated
      - ${DOCKER_RSA_PUB_FILE}:/tmp/.ssh/id_rsa.pub:delegated
      - .:/app:delegated
      - ./dev/null:/app/.git:delegated
      - ./dev/null:/app/.idea:delegated
      - ./dev/null:/app/node_modules:delegated
      - db-data:/var/lib/mysql
      - vendor-data:/app/vendor
      - cache-data:/app/storage
      - public-cache:/app/public/cache
      - cpresources:/app/public/cpresources
      - imagecache:/app/public/imagecache
    ports:
      - "${DOCKER_DB_PORT}:3306"
    networks:
      common:
  node:
    image: node:latest
    container_name: node-stmarkreformed
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ${DOCKER_RSA_FILE}:/tmp/.ssh/id_rsa:delegated
      - ${DOCKER_RSA_PUB_FILE}:/tmp/.ssh/id_rsa.pub:delegated
      - .:/app:delegated
      - ./dev/null:/app/.git:delegated
      - ./dev/null:/app/.idea:delegated
      - node-data:/app/node_modules
      - db-data:/var/lib/mysql
      - vendor-data:/app/vendor
      - cache-data:/app/storage
      - public-cache:/app/public/cache
      - cpresources:/app/public/cpresources
      - imagecache:/app/public/imagecache
    command: bash -c "sleep infinity & wait"
    networks:
      common:

volumes:
  vendor-data:
  cache-data:
  db-data:
  node-data:
  public-cache:
  cpresources:
  imagecache:

networks:
  common:
