version: '3.7'

services:
  app:
    restart: always
    env_file:
      - .env
      - .env.local
    image: ghcr.io/st-mark-reformed/stmarkreformed.com-app
    container_name: stmark-app
    environment:
      ENABLE_PHP_DEV_CONFIG: 1
      HOSTNAME: stmark-app
    ports:
      - "44232:80"
    volumes:
      - .:/var/www:delegated
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-dev_default
      - traefik.http.routers.stmark_local.entrypoints=web
      - traefik.http.routers.stmark_local.rule=Host(`stmark.localtest.me`)
      - traefik.http.routers.stmark_local.middlewares=https-redirect
      - traefik.http.routers.stmark_local-secure.entrypoints=websecure
      - traefik.http.routers.stmark_local-secure.tls=true
      - traefik.http.routers.stmark_local-secure.rule=Host(`stmark.localtest.me`)
    networks:
      - traefik
      - default

  db:
    restart: always
    env_file:
      - .env
      - .env.local
    image: ghcr.io/st-mark-reformed/stmarkreformed.com-db
    container_name: stmark-db
    environment:
      HOSTNAME: stmark-db
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "44230:3306"
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      traefik:
      default:
        aliases:
          - stmark-db

  redis:
    container_name: stmark-redis
    image: redis:alpine3.14
    volumes:
      - redis-volume:/data
    networks:
      default:
        aliases:
          - stmark-redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: stmark-elasticsearch
    environment:
      - cluster.name=es-docker-cluster
      - node.name=stmark-elasticsearch
      - cluster.initial_master_nodes=stmark-elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    expose:
      - "9200"
    networks:
      default:
        aliases:
          - stmark-elasticsearch

volumes:
  db-volume:
  elasticsearch-data-volume:
  redis-volume:

networks:
  traefik:
    name: traefik-dev_default
    external: true
