version: '3.7'

services:
  web:
    volumes:
      - vendor-volume:/opt/project/vendor

  php:
    volumes:
      - vendor-volume:/opt/project/vendor

  bg-sync-node-modules:
    container_name: stmark-bg-sync-node-modules
    image: cweagans/bg-sync
    volumes:
      - node-modules-volume:/source
      - ./node_modules:/destination
    environment:
      - SYNC_MAX_INOTIFY_WATCHES=40000
      - SYNC_VERBOSE=1
    privileged: true

  bg-sync-vendor:
    image: cweagans/bg-sync
    container_name: stmark-bg-sync-vendor
    volumes:
      - ./vendor:/source
      - vendor-volume:/destination
    environment:
      - SYNC_MAX_INOTIFY_WATCHES=40000
      - SYNC_VERBOSE=1
    privileged: true

volumes:
  node-modules-volume:
  vendor-volume:
