version: '3.7'

services:
  web:
    platform: linux/amd64
    build:
      target: dev
    volumes:
      - .:/opt/project:delegated
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/nginx.conf:delegated
      - ./docker/web/stmark.localtest.me.cert:/etc/letsencrypt/live/www.stmarkreformed.com/fullchain.pem:delegated
      - ./docker/web/stmark.localtest.me.key:/etc/letsencrypt/live/www.stmarkreformed.com/privkey.pem:delegated

  php:
    platform: linux/amd64
    build:
      target: dev
    volumes:
      - .:/opt/project:delegated

  db:
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/opt/project:delegated
