version: '3.7'

services:
  app:
    env_file:
      - .env
      - .env.local
    container_name: stmark-app
    image: ghcr.io/st-mark-reformed/stmarkreformed.com-app
    environment:
      HOSTNAME: stmark-app
    expose:
      - 80
    ports:
      - "44232:80"

  db:
    env_file:
      - .env
      - .env.local
    container_name: stmark-db
    image: ghcr.io/st-mark-reformed/stmarkreformed.com-db
    environment:
      HOSTNAME: stmark-db
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "44230:3306"
    networks:
      default:
        aliases:
          - stmark-db

  redis:
    container_name: stmark-redis
    image: redis:alpine3.14
    volumes:
      - redis-volume:/data
    networks:
      default:
        aliases:
          - stmark-redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: stmark-elasticsearch
    environment:
      - cluster.name=es-docker-cluster
      - node.name=stmark-elasticsearch
      - cluster.initial_master_nodes=stmark-elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    expose:
      - "9200"
    networks:
      default:
        aliases:
          - stmark-elasticsearch

volumes:
  db-volume:
  elasticsearch-data-volume:
  log-volume:
  redis-volume:
  storage-volume:
