version: '3.7'

services:
  utility:
    env_file: .env
    image: ubuntu:18.04
    restart: always
    container_name: stmark-utility
    volumes:
      - .:/opt/project
      - image-cache-volume:/image-cache-volume
      - files-volume:/files-volume
      - log-volume:/log-volume
      - public-cache-volume:/public-cache-volume
      - storage-volume:/storage-volume
      - uploads-volume:/uploads-volume
    command: bash -c "chmod +x /opt/project/docker/utility/prod.sh && /opt/project/docker/utility/prod.sh"

  web:
    build:
      target: prod
    restart: always
    volumes:
      - image-cache-volume:/opt/project/public/imagecache
      - files-volume:/opt/project/public/files
      - log-volume:/var/log
      - public-cache-volume:/opt/project/public/cache
      - storage-volume:/opt/project/storage
      - uploads-volume:/opt/project/public/uploads
      - nginx-master_certbot-conf-volume:/etc/letsencrypt

  php:
    build:
      target: prod
    restart: always
    volumes:
      - image-cache-volume:/opt/project/public/imagecache
      - files-volume:/opt/project/public/files
      - log-volume:/var/log
      - public-cache-volume:/opt/project/public/cache
      - storage-volume:/opt/project/storage
      - uploads-volume:/opt/project/public/uploads

  php-queue-runner-1:
    env_file: .env
    build:
      target: prod
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: always
    container_name: stmark-php-queue-runner-1
    environment:
      HOSTNAME: stmark-php-queue-runner-1
    volumes:
      - image-cache-volume:/opt/project/public/imagecache
      - files-volume:/opt/project/public/files
      - log-volume:/var/log
      - public-cache-volume:/opt/project/public/cache
      - storage-volume:/opt/project/storage
      - uploads-volume:/opt/project/public/uploads
    command: bash -c "chmod +x /opt/project/queueRunner.sh && /opt/project/queueRunner.sh"
    networks:
      default:
        aliases:
          - stmark-php-queue-runner-1

  php-queue-runner-2:
    env_file: .env
    build:
      target: prod
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: always
    container_name: stmark-php-queue-runner-2
    environment:
      HOSTNAME: stmark-php-queue-runner-2
    volumes:
      - image-cache-volume:/opt/project/public/imagecache
      - files-volume:/opt/project/public/files
      - log-volume:/var/log
      - public-cache-volume:/opt/project/public/cache
      - storage-volume:/opt/project/storage
      - uploads-volume:/opt/project/public/uploads
    command: bash -c "chmod +x /opt/project/queueRunner.sh && /opt/project/queueRunner.sh"
    networks:
      default:
        aliases:
          - stmark-php-queue-runner-2

  php-queue-runner-3:
    env_file: .env
    build:
      target: prod
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: always
    container_name: stmark-php-queue-runner-3
    environment:
      HOSTNAME: stmark-php-queue-runner-3
    volumes:
      - image-cache-volume:/opt/project/public/imagecache
      - files-volume:/opt/project/public/files
      - log-volume:/var/log
      - public-cache-volume:/opt/project/public/cache
      - storage-volume:/opt/project/storage
      - uploads-volume:/opt/project/public/uploads
    command: bash -c "chmod +x /opt/project/queueRunner.sh && /opt/project/queueRunner.sh"
    networks:
      default:
        aliases:
          - stmark-php-queue-runner-3

  db:
    restart: always
    volumes:
      - log-volume:/var/log

volumes:
  image-cache-volume:
  files-volume:
  log-volume:
  public-cache-volume:
  storage-volume:
  uploads-volume:
  nginx-master_certbot-conf-volume:
    external: true
