version: '3.7'

services:
  app:
    volumes:
      - .:/opt/project:delegated
    networks:
      web:
      default:
        aliases:
            - stmark.localtest.me
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-dev_default

      # Non-SSL Local
      - traefik.http.routers.stmark-local.entrypoints=web
      - traefik.http.routers.stmark-local.rule=Host(`stmark.localtest.me`)
      - traefik.http.routers.stmark-local.middlewares=https-redirect

      # Non-SSL Ngrok
      - traefik.http.routers.stmark-ngrok.entrypoints=web
      - traefik.http.routers.stmark-ngrok.rule=Host(`stmark.ngrok.io`)
      - traefik.http.routers.stmark-ngrok.middlewares=https-redirect

      # SSL Local
      - traefik.http.routers.stmark-secure-local.entrypoints=websecure
      - traefik.http.routers.stmark-secure-local.tls=true
      - traefik.http.routers.stmark-secure-local.rule=Host(`stmark.localtest.me`)

      # SSL Ngrok
      - traefik.http.routers.stmark-secure-ngrok.entrypoints=websecure
      - traefik.http.routers.stmark-secure-ngrok.tls=true
      - traefik.http.routers.stmark-secure-ngrok.rule=Host(`stmark.ngrok.io`)

  db:
    volumes:
      - .:/opt/project:delegated

networks:
  web:
    name: traefik-dev_default
    external: true
