field: a7845568-a0c6-44e5-8b75-3ef735f6ef8d # Page Builder
fieldLayouts:
  7091e0b0-79b9-4b20-ad14-0ad0173958e6:
    tabs:
      -
        elements:
          -
            fieldUid: d4e3e352-d099-4aab-9f65-175196a92487 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fab4b26c-20f2-4f6b-a4f9-93c660dfcd40 # Sub Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  d4e3e352-d099-4aab-9f65-175196a92487: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fab4b26c-20f2-4f6b-a4f9-93c660dfcd40: # Sub Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subHeading
    instructions: ''
    name: 'Sub Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: latestGalleries
name: 'Latest Galleries'
sortOrder: 4
