<?php
$suffix = 'SMRC Auth';
$pageTitle = isset($pageTitle) ? ($pageTitle . ' | ' . $suffix) : $suffix;
?>

<!DOCTYPE html>
<html lang="en" class="h-full bg-gray-50">
<head>
    <meta charset="UTF-8" />
    <title><?= $pageTitle ?></title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link rel="stylesheet" href="/assets/style.css">
    <link rel="icon" href="/favicon.ico">
</head>
<body class="h-full">
    <div class="relative z-10 h-full w-full">
        <?= $this->getSection('layoutContent') ?>
    </div>
</body>
</html>
