<?php

use App\Html\HtmlFormInputConfig;
use App\Html\HtmlPath;
use App\Html\ButtonConfig;
use App\LogIn\LogInFlashErrorMessages;
use BuzzingPixel\Templating\TemplateEngine;
use Psr\Container\ContainerInterface;

assert($this instanceof TemplateEngine);

/** @noinspection PhpUndefinedVariableInspection */
assert($di instanceof ContainerInterface);

$this->extends(HtmlPath::HTML_LAYOUT);

$errorMessages = $di->get(LogInFlashErrorMessages::class)->retrieveMessages();

$errorHeadline = $errorHeadline ?? 'An error occurred';

if ($errorMessages->count() > 1) {
    $errorHeadline = 'There were ' . $errorMessages->count() . ' errors';
}

$csrfTokenNameKey = $csrfTokenNameKey ?? '';
$csrfTokenName = $csrfTokenName ?? '';
$csrfTokenValueKey = $csrfTokenValueKey ?? '';
$csrfTokenValue = $csrfTokenValue ?? '';

$h2 = $h2 ?? $pageTitle ?? '';

$formAction = $formAction ?? null;

/** @var HtmlFormInputConfig[] $inputs */
$inputs = $inputs ?? [];

$submitButtonConfig = $submitButtonConfig ?? new ButtonConfig();

global $wrapperWidth;
$wrapperWidth = 'max-w-xl';
$this->extends(HtmlPath::CENTERED_WRAPPER_LAYOUT);
?>

<div class="flex flex-col justify-center text-left">
    <div class="sm:mx-auto sm:w-full">
        <?php if ($errorMessages->hasMessages()): ?>
            <div class="rounded-lg bg-red-50 p-4 mb-6">
                <div class="flex">
                    <div class="shrink-0">
                        <svg viewBox="0 0 20 20" fill="currentColor" data-slot="icon" aria-hidden="true" class="size-5 text-red-400">
                            <path d="M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16ZM8.28 7.22a.75.75 0 0 0-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 1 0 1.06 1.06L10 11.06l1.72 1.72a.75.75 0 1 0 1.06-1.06L11.06 10l1.72-1.72a.75.75 0 0 0-1.06-1.06L10 8.94 8.28 7.22Z" clip-rule="evenodd" fill-rule="evenodd" />
                        </svg>
                    </div>
                    <div class="ml-3">
                        <h3 class="text-base font-semibold text-red-800">
                            <?= $errorHeadline ?>
                        </h3>
                        <div class="mt-2 text-sm text-red-700">
                            <ul role="list" class="list-image-none space-y-1">
                                <?php foreach ($errorMessages->messages as $message): ?>
                                    <li>
                                        <?php if ($message->body === ''): ?>
                                            <?= $this->html($message->title) ?>
                                        <?php else: ?>
                                            <div class="font-bold">
                                                <?= $this->html($message->title) ?>
                                            </div>
                                            <?= $this->html($message->body) ?>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <div class="sm:mx-auto sm:w-full sm:max-w-md mb-10">
            <h2 class="text-center text-2xl font-bold tracking-tight text-bronze-lightened-1">
                <?=$this->html($h2)?>
            </h2>
        </div>
        <form
            id="htmlFormLayoutForm"
            method="POST"
            action="<?=$formAction?>"
            class="space-y-6"
            novalidate
        >
            <input
                type="hidden"
                name="<?= $csrfTokenNameKey ?>"
                value="<?= $csrfTokenName ?>"
            >
            <input
                type="hidden"
                name="<?= $csrfTokenValueKey ?>"
                value="<?= $csrfTokenValue ?>"
            >
            <?php foreach ($inputs as $input): ?>
                <?= $this->partial($input->type->templatePath(), [
                    'input' => $input,
                ]) ?>
            <?php endforeach; ?>
            <div>
                <?php
                    $commonClasses = 'flex w-full justify-center rounded-lg px-3 py-3 text-base font-semibold shadow-xs';
                    $activeClasses = 'text-white bg-crimson hover:bg-crimson-dark cursor-pointer';
                    $inactiveClasses = 'text-gray-300 bg-gray-500 cursor-default';
                ?>
                <button
                    id="htmlFormLayoutSubmitButton"
                    type="submit"
                    class="<?=implode(' ', [
                        $commonClasses,
                        $activeClasses,
                    ])?>"
                    data-common-classes="<?=$commonClasses?>"
                    data-active-classes="<?=$activeClasses?>"
                    data-inactive-classes="<?=$inactiveClasses?>"
                >
                    <span class="block relative">
                        <div
                            id="htmlFormLayoutSubmitLoader"
                            class="absolute hidden"
                            style="left: -1.3rem; top: 0.2rem"
                        >
                            <svg aria-hidden="true" class="w-4 h-4 text-gray-200 animate-spin fill-saddle-brown-lightened-2" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
                                <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
                            </svg>
                            <span class="sr-only">Loading...</span>
                        </div>
                        <?=$submitButtonConfig->content?>
                        <?php if ($submitButtonConfig->glyph !== null): ?>
                            <span class="inline-block align-middle ml-1" style="margin-top: -5px">
                                <?=$this->partial($submitButtonConfig->glyph->value, [
                                    'class' => 'size-4 inline-block align-middle',
                                ])?>
                            </span>
                        <?php endif; ?>
                    </span>
                </button>
            </div>
        </form>
        <script>
            function htmlFormLayoutFormSetUp () {
                /** @type {HTMLElement} */
                const form = document.getElementById(
                    'htmlFormLayoutForm',
                );

                /** @type {HTMLElement} */
                const submitButton = document.getElementById(
                    'htmlFormLayoutSubmitButton',
                );

                /** @type {HTMLElement} */
                const submitLoader = document.getElementById(
                    'htmlFormLayoutSubmitLoader',
                );

                form.addEventListener('submit', function () {
                    submitButton.className = [
                        submitButton.dataset.commonClasses,
                        submitButton.dataset.inactiveClasses,
                    ].join(' ');

                    submitLoader.classList.remove('hidden');
                });
            }

            htmlFormLayoutFormSetUp();
        </script>
    </div>
</div>
