field: c9504fe8-d2fb-458b-a2e9-f8872585919a
fieldLayouts:
  36d1a1a4-81bf-496d-bbd4-22cef03272c3:
    tabs:
      -
        elements:
          -
            fieldUid: e355e9ca-6733-4125-823c-1111afcb79eb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 65d4cdb4-f28e-469a-a25f-420675afd673
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0d9de0c2-3e02-4799-905a-dc37c9ab8299
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9541534e-7593-41ec-b0c8-5b12cecf235c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1619a0e9-2a7f-4450-ad7b-9eb6f10a435d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fb27befa-4657-425c-b961-eeace2f94dc4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0d9de0c2-3e02-4799-905a-dc37c9ab8299:
    contentColumnType: string
    fieldGroup: null
    handle: subheading
    instructions: ''
    name: Subheading
    searchable: true
    settings:
      byteLimit: null
      charLimit: 50
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  1619a0e9-2a7f-4450-ad7b-9eb6f10a435d:
    contentColumnType: text
    fieldGroup: null
    handle: callToAction
    instructions: ''
    name: 'Call To Action'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Text
                -
                  - handle
                  - text
                -
                  - width
                  - 50%
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Link
                -
                  - handle
                  - link
                -
                  - width
                  - 50%
                -
                  - type
                  - singleline
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  65d4cdb4-f28e-469a-a25f-420675afd673:
    contentColumnType: string
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: 50
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9541534e-7593-41ec-b0c8-5b12cecf235c:
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes:
        - fe2952ce-382a-4470-8f04-a7bdd1b48f66
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  e355e9ca-6733-4125-823c-1111afcb79eb:
    contentColumnType: string
    fieldGroup: null
    handle: options
    instructions: ''
    name: Options
    searchable: true
    settings:
      multi: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Align Headings on Left'
            -
              - value
              - alignHeadingsOnLeft
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Center Align Block'
            -
              - value
              - centerAlignBlock
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Red Block Background'
            -
              - value
              - redBlockBackground
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No Top Padding'
            -
              - value
              - noTopPadding
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Checkboxes
  fb27befa-4657-425c-b961-eeace2f94dc4:
    contentColumnType: string
    fieldGroup: null
    handle: blockBackgroundImage
    instructions: ''
    name: 'Block Background Image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:fe2952ce-382a-4470-8f04-a7bdd1b48f66'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:fe2952ce-382a-4470-8f04-a7bdd1b48f66'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: basicBlock
name: 'Basic Block'
sortOrder: 1
