field: c9504fe8-d2fb-458b-a2e9-f8872585919a # Old Page Builder
fieldLayouts:
  f160cabb-ff49-4ee2-8bb2-49e06d800438:
    tabs:
      -
        elements:
          -
            fieldUid: 96489851-57e6-4cdd-9f3c-d2e785615f32 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1a0827bd-1b3c-4260-9328-30c8c7307478 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fb809945-7807-4e81-9c34-4ff030f0888a # Links
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1a0827bd-1b3c-4260-9328-30c8c7307478: # Subheading
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: subheading
    instructions: ''
    name: Subheading
    searchable: true
    settings:
      byteLimit: null
      charLimit: 50
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  96489851-57e6-4cdd-9f3c-d2e785615f32: # Heading
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: 50
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fb809945-7807-4e81-9c34-4ff030f0888a: # Links
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: links
    instructions: ''
    name: Links
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Text
                -
                  - handle
                  - text
                -
                  - width
                  - 50%
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Link
                -
                  - handle
                  - link
                -
                  - width
                  - 50%
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: linkListBlock
name: 'Link List Block'
sortOrder: 2
