field: c9504fe8-d2fb-458b-a2e9-f8872585919a # Old Page Builder
fieldLayouts:
  8a28bc4d-8d07-44df-a5db-0d0e38db368c:
    tabs:
      -
        elements:
          -
            fieldUid: df286b48-0507-4f99-9892-1f542903143c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7e651c1f-ddb7-4bd0-9842-d0d8b71f4671 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 16af453e-7756-4645-b749-cdee119c0d14 # Address
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 51c9e48c-507e-4e3d-8152-0dba14ef55c3 # Address Line 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5df4f883-59cf-4b67-b323-6330a84cd1cd # City
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ff6f181e-01c5-4ca2-815d-5b737efab5d6 # State
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 505b895d-c9b1-4296-99ae-d2bef20459c3 # Zip
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1f642a1f-8157-48c8-b796-705f62303756 # Latitude
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a9201e3f-ed7d-463f-b19f-20f487917a4a # Longitude
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8f9ce4e3-aa79-49a5-9857-a5a0eb2396c6 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1f642a1f-8157-48c8-b796-705f62303756: # Latitude
    columnSuffix: null
    contentColumnType: 'decimal(40,30)'
    fieldGroup: null
    handle: latitude
    instructions: ''
    name: Latitude
    searchable: true
    settings:
      decimals: '30'
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  5df4f883-59cf-4b67-b323-6330a84cd1cd: # City
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: city
    instructions: ''
    name: City
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7e651c1f-ddb7-4bd0-9842-d0d8b71f4671: # Subheading
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: subheading
    instructions: ''
    name: Subheading
    searchable: true
    settings:
      byteLimit: null
      charLimit: 30
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8f9ce4e3-aa79-49a5-9857-a5a0eb2396c6: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes:
        - fe2952ce-382a-4470-8f04-a7bdd1b48f66
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  16af453e-7756-4645-b749-cdee119c0d14: # Address
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: address
    instructions: ''
    name: Address
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  51c9e48c-507e-4e3d-8152-0dba14ef55c3: # Address Line 2
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: addressLine2
    instructions: ''
    name: 'Address Line 2'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  505b895d-c9b1-4296-99ae-d2bef20459c3: # Zip
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: zip
    instructions: ''
    name: Zip
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a9201e3f-ed7d-463f-b19f-20f487917a4a: # Longitude
    columnSuffix: null
    contentColumnType: 'decimal(40,30)'
    fieldGroup: null
    handle: longitude
    instructions: ''
    name: Longitude
    searchable: true
    settings:
      decimals: '30'
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  df286b48-0507-4f99-9892-1f542903143c: # Heading
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: 30
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ff6f181e-01c5-4ca2-815d-5b737efab5d6: # State
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: state
    instructions: ''
    name: State
    searchable: true
    settings:
      byteLimit: null
      charLimit: 2
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: mapBlock
name: 'Map Block'
sortOrder: 3
