field: 47434acf-158e-4fd3-8220-8a5283b1e31d
fieldLayouts:
  651c49de-7100-4230-9a74-de73b6e481cd:
    tabs:
      -
        elements:
          -
            fieldUid: c6aca555-901d-4a2c-9e86-32cc8a9c874a
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 590175c1-55b0-415f-998e-af7c44a7baa7
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 71694359-63b4-4ce1-9ac4-dfcd16278c23
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7e6f2771-2825-4ca6-93ee-9ad025766073
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d9538c13-7e83-4eb2-bef8-656ddf57d4d1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  590175c1-55b0-415f-998e-af7c44a7baa7:
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: ''
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  71694359-63b4-4ce1-9ac4-dfcd16278c23:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: minValue
    instructions: ''
    name: 'Min Value'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
  7e6f2771-2825-4ca6-93ee-9ad025766073:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: maxValue
    instructions: ''
    name: 'Max Value'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
  c6aca555-901d-4a2c-9e86-32cc8a9c874a:
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  d9538c13-7e83-4eb2-bef8-656ddf57d4d1:
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
handle: number
name: Number
sortOrder: 5
