field: 47434acf-158e-4fd3-8220-8a5283b1e31d
fieldLayouts:
  3c0dd5ee-8454-4ee6-8490-0772cfcafb63:
    tabs:
      -
        elements:
          -
            fieldUid: 329dc41c-c23b-46d7-ad54-b4546924df24
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f43f4599-81dc-4112-90a6-51736d838ed9
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8eb72b5c-47ec-4754-9f3b-ae4a16bc49e0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 477c8507-3199-4ea6-a361-367af49b7e8c
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f59688d0-f8bd-4e15-8b92-364374c932c8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  329dc41c-c23b-46d7-ad54-b4546924df24:
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  477c8507-3199-4ea6-a361-367af49b7e8c:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: initialRows
    instructions: ''
    name: 'Initial Rows'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '2'
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
  8eb72b5c-47ec-4754-9f3b-ae4a16bc49e0:
    contentColumnType: text
    fieldGroup: null
    handle: placeholder
    instructions: ''
    name: Placeholder
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  f43f4599-81dc-4112-90a6-51736d838ed9:
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: ''
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  f59688d0-f8bd-4e15-8b92-364374c932c8:
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
handle: paragraph
name: Paragraph
sortOrder: 2
