field: c9504fe8-d2fb-458b-a2e9-f8872585919a # Old Page Builder
fieldLayouts:
  92176789-8ea5-4539-8964-c5fefa2c99a4:
    tabs:
      -
        elements:
          -
            fieldUid: 076138c8-eca9-475a-a69b-b912c2dae610 # Stripe Payment Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  076138c8-eca9-475a-a69b-b912c2dae610: # Stripe Payment Form
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: stripePaymentForm
    instructions: ''
    name: 'Stripe Payment Form'
    searchable: false
    settings:
      allowMultipleSources: false
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: '*'
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: enupal\stripe\fields\StripePaymentForms
handle: stripeForm
name: 'Stripe Form'
sortOrder: 10
