field: a7845568-a0c6-44e5-8b75-3ef735f6ef8d # Page Builder
fieldLayouts:
  f64ce190-4cd5-469c-8a93-24fc5dfb9559:
    tabs:
      -
        elements:
          -
            fieldUid: b0f85794-2ed8-4526-977b-0099ead28ee1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6d75b4fe-9798-4b39-84b6-a6164b04ce9c # Sub Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6d75b4fe-9798-4b39-84b6-a6164b04ce9c: # Sub Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subHeading
    instructions: ''
    name: 'Sub Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b0f85794-2ed8-4526-977b-0099ead28ee1: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: upcomingEvents
name: 'Upcoming Events'
sortOrder: 3
