#!/usr/bin/with-contenv bash
set -e

ENABLE_XDEBUG="${ENABLE_XDEBUG:-0}"

#
# Enable Xdebug right before running the PHP process to avoid unnecessary
# slowness during startup
#

if [ "$ENABLE_XDEBUG" = "1" ]
then
    cp ${PHP_INI_DIR}/disabled/xdebug.ini ${PHP_INI_DIR}/conf.d/
fi

if [ "$DISABLE_PHP_FPM" != "1" ]
then
    exec php-fpm -F
fi
