<?php

declare(strict_types=1);

use BuzzingPixel\Templating\TemplateEngine;

assert($this instanceof TemplateEngine);

$userEmail = $userEmail ?? '';
assert(is_string($userEmail));
?>

<div class="flex flex-col justify-center">
    <div class="sm:mx-auto">
        <div class="sm:mx-auto sm:w-full sm:max-w-md mb-6 px-2">
            <h2 class="mt-4 text-center text-2xl/9 font-bold tracking-tight text-rx-light-blue-600">
                You are logged in to SMRC
            </h2>
            <p class="mt-1 text-lg text-center font-extralight text-pretty text-rx-gray-500 sm:text-xl/8">
                as <span class="font-bold"><?= $userEmail ?></span>
            </p>
            <div class="mt-10 flex items-center justify-center gap-x-6">
                <a
                    href="/log-out"
                    class="rounded-lg bg-crimson hover:bg-crimson-dark px-3.5 py-3 text-sm font-semibold text-white shadow-xs"
                >
                    Log Out
                </a>
            </div>
        </div>
    </div>
</div>
