<?php

declare(strict_types=1);

use App\Html\ButtonRows;
use App\Html\HtmlPath;
use BuzzingPixel\Templating\TemplateEngine;

assert($this instanceof TemplateEngine);

$userEmail = $userEmail ?? '';
assert(is_string($userEmail));

/** @var ButtonRows $buttonRows */
$buttonRows = $buttonRows ?? new ButtonRows();
?>

<div class="flex flex-col justify-center">
    <div class="sm:mx-auto">
        <div class="sm:mx-auto sm:w-full sm:max-w-md mb-6 px-2">
            <h2 class="mt-4 text-center text-2xl/9 font-bold tracking-tight text-rx-light-blue-600">
                You are logged in to SMRC
            </h2>
            <p class="mt-1 text-lg text-center font-extralight text-pretty text-rx-gray-500 sm:text-xl/8">
                as <span class="font-bold"><?= $userEmail ?></span>
            </p>
            <?=$this->partial(HtmlPath::BUTTON_ROWS, [
                'buttonRows' => $buttonRows,
            ])?>
        </div>
    </div>
</div>
