services:
  proxy:
    restart: always
    depends_on:
      - web
      - app
    env_file:
      - ./proxy/.env
      - ./proxy/.env.local
    image: ghcr.io/st-mark-reformed/stmarkreformed.com-proxy
    container_name: stmark-proxy
    environment:
      HOSTNAME: stmark-proxy
    expose:
      - 80
    networks:
      traefik:
      default:
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-dev_default
      - traefik.http.routers.stmark_local.entrypoints=web
      - traefik.http.routers.stmark_local.rule=Host(`stmark.localtest.me`)
      - traefik.http.routers.stmark_local.middlewares=https-redirect
      - traefik.http.routers.stmark_local-secure.entrypoints=websecure
      - traefik.http.routers.stmark_local-secure.tls=true
      - traefik.http.routers.stmark_local-secure.rule=Host(`stmark.localtest.me`)
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/conf.d/default.conf.template

  web:
    stdin_open: true
    env_file:
      - ./web/.env
      - ./web/.env.local
    image: ghcr.io/st-mark-reformed/stmarkreformed.com-web
    container_name: stmark-web
    environment:
      HOSTNAME: stmark-web
      NODE_ENV: development
    healthcheck:
      disable: true
      test: '0'
    command:
      - "npm"
      - "run"
      - "dev"
    volumes:
      - ./web/.bash_history:/root/.bash_history:delegated
      - ../web:/app:delegated
    expose:
      - 80
    networks:
      traefik:
      default:
        aliases:
          - internal_web_container

  api:
    restart: always
    env_file:
      - api/.env
      - api/.env.local
    image: ghcr.io/st-mark-reformed/stmarkreformed.com-api
    container_name: stmark-api
    environment:
      ENABLE_XDEBUG: 1
      ENABLE_PHP_DEV_CONFIG: 1
      HOSTNAME: stmark-app
    volumes:
      - ./api/.bash_history:/root/.bash_history:delegated
      - ../api:/var/www:delegated
    networks:
      traefik:
      default:
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-dev_default
      - traefik.http.routers.stmark_api_local.entrypoints=web
      - traefik.http.routers.stmark_api_local.rule=Host(`api.stmark.localtest.me`)
      - traefik.http.routers.stmark_api_local.middlewares=https-redirect
      - traefik.http.routers.stmark_api_local-secure.entrypoints=websecure
      - traefik.http.routers.stmark_api_local-secure.tls=true
      - traefik.http.routers.stmark_api_local-secure.rule=Host(`api.stmark.localtest.me`)
    healthcheck:
      disable: true
      test: "1"

  app:
    restart: always
    env_file:
      - application/.env
      - application/.env.local
    image: ghcr.io/st-mark-reformed/stmarkreformed.com-app
    container_name: stmark-app
    environment:
      ENABLE_PHP_DEV_CONFIG: 1
      HOSTNAME: stmark-app
    ports:
      - "44232:80"
    volumes:
      - ../craft-cms:/var/www:delegated
    networks:
      traefik:
      default:
        aliases:
          - internal_craft_container

  app-scheduled-task-runner:
    restart: always
    env_file:
      - application/.env
      - application/.env.local
    image: ghcr.io/st-mark-reformed/stmarkreformed.com-app-schedule-runner
    container_name: app-scheduled-task-runner
    environment:
      - ENABLE_PHP_DEV_CONFIG=1
      - HOSTNAME=app-scheduled-task-runner
    volumes:
      - ../craft-cms:/var/www:delegated
    healthcheck:
      disable: true
      test: "1"

  app-queue-consumer-1:
    restart: always
    env_file:
      - application/.env
      - application/.env.local
    image: ghcr.io/st-mark-reformed/stmarkreformed.com-app
    container_name: app-queue-consumer-1
    environment:
      - ENABLE_PHP_DEV_CONFIG=1
      - HOSTNAME=app-queue-consumer-1
    volumes:
      - ../craft-cms:/var/www:delegated
    healthcheck:
      disable: true
      test: "1"
    entrypoint: >-
      /bin/bash -c
      "echo 'while /usr/local/bin/php /var/www/craft queue/run --interactive=0 2>&1; do sleep 0.2; done' > /runner.sh
      && chmod +x /runner.sh
      && /runner.sh"

  db:
    restart: always
    env_file:
      - application/.env
      - application/.env.local
    image: ghcr.io/st-mark-reformed/stmarkreformed.com-db
    container_name: stmark-db
    environment:
      HOSTNAME: stmark-db
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "44230:3306"
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      traefik:
      default:
        aliases:
          - stmark-db

  redis:
    container_name: stmark-redis
    image: redis:alpine3.14
    volumes:
      - redis-volume:/data
    networks:
      default:
        aliases:
          - stmark-redis

## TODO: Try to get this working on dev again sometime
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: stmark-elasticsearch
    environment:
      - cluster.name=es-docker-cluster
      - node.name=stmark-elasticsearch
      - cluster.initial_master_nodes=stmark-elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    expose:
      - "9200"
    networks:
      default:
        aliases:
          - stmark-elasticsearch

volumes:
  db-volume:
  elasticsearch-data-volume:
  redis-volume:

networks:
  traefik:
    name: traefik-dev_default
    external: true
