fieldLayouts:
  94fe7ef7-886e-4166-81fb-279fe682f652:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 799005b5-502a-4951-bb7e-ae247d00979c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ee082c58-0248-40c1-be7f-ecbbd205f56e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e13796c0-a36c-490c-bf23-eb7f25d5465f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b149c792-7a23-44b8-b08b-12fd4059475d
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: de88a8f8-2563-459e-8a52-b3ad2f0ec006
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 83ae5632-273d-44d5-b592-476a39460f51
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Publish
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 0bb8ab16-3c86-4ffb-86da-18c4e22a554e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a5663b9c-311e-405f-a780-b856c4cd8464
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b153d5f7-fd35-4731-9437-eb1333cdc3e2
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 98eceee6-f51c-4e12-b27e-8af4e80fb147
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: news
hasTitleField: true
name: News
section: 51c0f62a-b5a5-4135-bc90-471528d63f56
sortOrder: 1
titleFormat: ''
