handle: news
name: News
siteSettings:
  94e92402-bc7d-4413-bc65-a236d81d53aa:
    hasUrls: true
    template: ''
    uriFormat: 'news/category/{slug}'
structure:
  maxLevels: '1'
  uid: 164b4045-d305-42de-b283-5bd199b4d34e
