handle: pastorsPage
name: 'Pastor''s Page'
siteSettings:
  94e92402-bc7d-4413-bc65-a236d81d53aa:
    hasUrls: true
    template: ''
    uriFormat: 'pastors-page/category/{slug}'
structure:
  maxLevels: '1'
  uid: e742bad7-11d7-4086-8ec9-54240e6e881a
