columnSuffix: jikmsgto
contentColumnType: boolean
fieldGroup: c66e62d9-2ca8-4489-8c97-3f4dca8ccb60 # Common
handle: excludeFromFeatured
instructions: ''
name: 'Exclude From Featured'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
