contentColumnType: string
fieldGroup: c67a7c62-3fbd-43ac-86c6-32c299b87bfe # Users
handle: slugField
instructions: ''
name: Slug
searchable: '1'
settings:
  charLimit: ''
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
