baseUrl: 'http://stmarkreformed.test/'
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'St. Mark Reformed Church'
primary: true
siteGroup: 29f855c0-8761-4086-ae93-dcda8685d73c # St. Mark Reformed Church
sortOrder: 1
