columnSuffix: null
contentColumnType: string
fieldGroup: c67a7c62-3fbd-43ac-86c6-32c299b87bfe # Users
handle: associatedUserAccount
instructions: ''
name: 'Associated User Account'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: 'Add User'
  showSiteMenu: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Users
