contentColumnType: string
fieldGroup: a3adb82d-453d-4ae5-89d5-0f9b818b8d60 # Messages
handle: audio
instructions: ''
name: Audio
searchable: '1'
settings:
  allowedKinds:
    - audio
  defaultUploadLocationSource: 'volume:1de9d950-2b2b-4b09-957e-cc2396093495'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add an audio file'
  singleUploadLocationSource: 'volume:1de9d950-2b2b-4b09-957e-cc2396093495'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:1de9d950-2b2b-4b09-957e-cc2396093495'
  targetSiteId: null
  useSingleFolder: '1'
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
