contentColumnType: string
fieldGroup: 27b7be51-9d75-42da-9b5f-b2e1fb678ed6 # SEO
handle: customShareImage
instructions: ''
name: 'Custom Share Image'
searchable: '1'
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:fe2952ce-382a-4470-8f04-a7bdd1b48f66'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add an image'
  singleUploadLocationSource: 'volume:fe2952ce-382a-4470-8f04-a7bdd1b48f66'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:fe2952ce-382a-4470-8f04-a7bdd1b48f66'
  targetSiteId: null
  useSingleFolder: '1'
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
