columnSuffix: knudlrmz
contentColumnType: boolean
fieldGroup: c66e62d9-2ca8-4489-8c97-3f4dca8ccb60 # Common
handle: enableStaticCache
instructions: ''
name: 'Enable static cache'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
