contentColumnType: string
fieldGroup: 93012d1f-1633-417a-81d5-8f4b4e0ea023
handle: gallery
instructions: ''
name: Gallery
searchable: '1'
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:fe2952ce-382a-4470-8f04-a7bdd1b48f66'
  defaultUploadLocationSubpath: 'galleries/{slug}'
  limit: ''
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add images'
  singleUploadLocationSource: 'volume:fe2952ce-382a-4470-8f04-a7bdd1b48f66'
  singleUploadLocationSubpath: 'galleries/{slug}'
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: '1'
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
