contentColumnType: text
fieldGroup: c66e62d9-2ca8-4489-8c97-3f4dca8ccb60 # Common
handle: heroSubheading
instructions: ''
name: 'Hero Subheading'
searchable: '1'
settings:
  charLimit: '50'
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
