columnSuffix: pkvzzqre
contentColumnType: text
fieldGroup: c66e62d9-2ca8-4489-8c97-3f4dca8ccb60 # Common
handle: heroDarkeningOverlayOpacity
instructions: ''
name: 'Hero Darkening Overlay Opacity'
searchable: false
settings:
  initialRows: 8
  options: "min: 0,\r\nmax: 100,\r\nfrom: 0,\r\nstep: 10,\r\nhide_min_max: true"
translationKeyFormat: null
translationMethod: none
type: lewisjenkins\craftrangeslider\fields\RangeSlider
