contentColumnType: string
fieldGroup: c66e62d9-2ca8-4489-8c97-3f4dca8ccb60
handle: heroHeading
instructions: 'The entry title will be used if left blank'
name: 'Hero Heading'
searchable: '1'
settings:
  charLimit: '50'
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
