contentColumnType: string
fieldGroup: c66e62d9-2ca8-4489-8c97-3f4dca8ccb60
handle: hymnOfTheMonthPracticeTracks
instructions: ''
name: 'Hymn of the Month Practice Tracks'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - audio
  defaultUploadLocationSource: 'volume:fe2952ce-382a-4470-8f04-a7bdd1b48f66'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:6baa0e06-2c61-4aa9-bb22-249b9b32da5c' # Files Above Webroot
  singleUploadLocationSubpath: '{slug}/audio'
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
