contentColumnType: string
fieldGroup: c66e62d9-2ca8-4489-8c97-3f4dca8ccb60 # Common
handle: importSearchString
instructions: ''
name: 'Import Search String'
searchable: '1'
settings:
  charLimit: ''
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
