columnSuffix: ggibslgy
contentColumnType: text
fieldGroup: c66e62d9-2ca8-4489-8c97-3f4dca8ccb60 # Common
handle: location
instructions: ''
name: Location
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
