columnSuffix: null
contentColumnType: string
fieldGroup: e91f5555-0d06-411a-a55c-c24f14632bf4 # Pages
handle: pageBuilder
instructions: ''
name: 'Page Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagebuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
