contentColumnType: string
fieldGroup: e91f5555-0d06-411a-a55c-c24f14632bf4
handle: pageOptions
instructions: ''
name: 'Page Options'
searchable: '1'
settings:
  options:
    -
      __assoc__:
        -
          - default
          - ''
        -
          - label
          - 'Show SubNav'
        -
          - value
          - showSubnav
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
