contentColumnType: string
fieldGroup: c66e62d9-2ca8-4489-8c97-3f4dca8ccb60 # Common
handle: resourceDownloads
instructions: ''
name: 'Resource Downloads'
searchable: true
settings:
  contentTable: '{{%matrixcontent_resourcedownloads}}'
  localizeBlocks: false
  maxBlocks: ''
  minBlocks: ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
