contentColumnType: string
fieldGroup: 27b7be51-9d75-42da-9b5f-b2e1fb678ed6 # SEO
handle: seoTitle
instructions: ''
name: 'SEO Title'
searchable: '1'
settings:
  charLimit: '60'
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
