contentColumnType: text
fieldGroup: c66e62d9-2ca8-4489-8c97-3f4dca8ccb60
handle: shortDescription
instructions: ''
name: 'Short Description'
searchable: '1'
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
