contentColumnType: string
fieldGroup: a3adb82d-453d-4ae5-89d5-0f9b818b8d60 # Messages
handle: speaker
instructions: ''
name: Speaker
searchable: '1'
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: 'Add a speaker'
  source: null
  sources:
    - 'group:ee405175-77ba-4896-82e4-85669574f92a'
  targetSiteId: null
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Users
