columnSuffix: null
contentColumnType: string
fieldGroup: e91f5555-0d06-411a-a55c-c24f14632bf4 # Pages
handle: standardPageBuilder
instructions: ''
name: 'Old Page Builder'
searchable: true
settings:
  contentTable: '{{%matrixcontent_standardpagebuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
