contentColumnType: string
fieldGroup: e91f5555-0d06-411a-a55c-c24f14632bf4 # Pages
handle: subNavTitleOverride
instructions: ''
name: 'Sub Nav Title Override'
searchable: '1'
settings:
  charLimit: '50'
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
