contentColumnType: boolean
fieldGroup: c66e62d9-2ca8-4489-8c97-3f4dca8ccb60 # Common
handle: useShortHeader
instructions: ''
name: 'Use Short Header?'
searchable: false
settings:
  default: '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
