dateModified: 1634871970
email:
  fromEmail: info@stmarkreformed.com
  fromName: 'St. Mark Reformed Church'
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: tls
    host: smtp.mandrillapp.com
    password: $SMTP_PASSWORD
    port: '587'
    timeout: '30'
    useAuthentication: '1'
    username: info@buzzingpixel.com
  transportType: craft\mail\transportadapters\Smtp
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0bb8ab16-3c86-4ffb-86da-18c4e22a554e: 'Search Engine Indexing' # Search Engine Indexing
    0bfb38a0-09a7-4e91-89f8-eacb1cc78129: 'Basic Block' # Basic Block
    0d9de0c2-3e02-4799-905a-dc37c9ab8299: Subheading # Subheading
    0e14aaf7-e012-407f-a946-4531b9b59d3b: Globals # Globals
    1a0827bd-1b3c-4260-9328-30c8c7307478: Subheading # Subheading
    1df46fad-0886-4911-9132-137b6262c9ff: Heading # Heading
    1f77c244-ce0c-40e5-b771-799dd4fe6d0c: 'Custom Feature' # Custom Feature
    1f642a1f-8157-48c8-b796-705f62303756: Latitude # Latitude
    1fd7bdfe-3297-4602-90a4-7bbb4671eac3: 'Message Text' # Message Text
    2a9f1934-7a1f-41c3-bfdc-565035a5687f: 'Pastor''s Page Categories' # Pastor's Page Categories
    2a87f914-8ca0-4ff5-816f-eeed96eae0ab: 'Title or Honorific' # Title or Honorific
    5df4f883-59cf-4b67-b323-6330a84cd1cd: City # City
    5e1b8bc2-ba40-47cd-a9c4-438c1a793250: 'Internal Audio' # Internal Audio
    06ab3828-e4b9-4411-b012-c79e8d0dcd93: Excerpt # Excerpt
    6b75c664-339f-4a28-b126-60b34b55efce: 'Twitter URL' # Twitter URL
    6baa0e06-2c61-4aa9-bb22-249b9b32da5c: 'Files Above Webroot' # Files Above Webroot
    6bc8ff92-bd06-4bc8-aa10-5eb44afa22cf: 'Instagram URL' # Instagram URL
    6e55c0af-73fd-4439-b563-1ace6387eda8: 'Stripe Form' # Stripe Form
    6e6660c3-e157-450f-a37e-ac8464ce38ff: Tags # Tags
    7aa1e2e9-fcc5-4e79-b8ea-322145910185: 'Hero Upper CTA' # Hero Upper CTA
    7e5beee3-8da3-428c-9d03-dfe089f86b20: 'Hero Paragraph' # Hero Paragraph
    7e651c1f-ddb7-4bd0-9842-d0d8b71f4671: Subheading # Subheading
    07efee91-98b9-462b-824d-885cbf31780d: 'Latest Types' # Latest Types
    8e41a4a3-46e9-41d1-bb64-46f3cd0979c0: 'Import Search String' # Import Search String
    8f9ce4e3-aa79-49a5-9857-a5a0eb2396c6: Body # Body
    8f73d9f8-3435-4396-bb8f-e729910f2665: Gallery # Gallery
    16af453e-7756-4645-b749-cdee119c0d14: Address # Address
    16f9c03e-c104-4d75-84e9-479cd71b1d32: 'Gallery Showcase' # Gallery Showcase
    27b7be51-9d75-42da-9b5f-b2e1fb678ed6: SEO # SEO
    29f855c0-8761-4086-ae93-dcda8685d73c: 'St. Mark Reformed Church' # St. Mark Reformed Church
    32d76b8c-d3f3-45cf-8b3d-55991f485a16: Bio # Bio
    40a813c7-72ac-4043-b70b-718c0a7868b3: 'Link List Block' # Link List Block
    46e9048c-cfef-4f69-acd7-cd03439b3867: 'Use Short Hero?' # Use Short Hero?
    51c9e48c-507e-4e3d-8152-0dba14ef55c3: 'Address Line 2' # Address Line 2
    65d4cdb4-f28e-469a-a25f-420675afd673: Heading # Heading
    83ae5632-273d-44d5-b592-476a39460f51: 'Entry Builder' # Entry Builder
    84f0c3bc-62d3-4031-83c9-053e7a1fc6b2: General # General
    94e92402-bc7d-4413-bc65-a236d81d53aa: 'St. Mark Reformed Church' # St. Mark Reformed Church
    98eceee6-f51c-4e12-b27e-8af4e80fb147: 'Custom Share Image' # Custom Share Image
    0214b210-9d5a-47f7-8e2c-1dc100c5a952: Date # Date
    261a469a-71d2-46af-8ca5-7b25e2a168f1: Pages # Pages
    292cba0e-342e-4846-9263-6b573384de88: 'Feature Latest' # Feature Latest
    0363b404-b48e-4cdb-8a99-253db50b2d17: 'Select a series to display' # Select a series to display
    505b895d-c9b1-4296-99ae-d2bef20459c3: Zip # Zip
    714e71ca-d308-4ed3-8a66-351e750b7b70: Speaker # Speaker
    922bdd2b-20e9-41d4-92bc-007b8452a18e: Slug # Slug
    926ff203-b918-45b0-b2a6-bfa4604b465f: 'Internal Message Series' # Internal Message Series
    1619a0e9-2a7f-4450-ad7b-9eb6f10a435d: 'Call To Action' # Call To Action
    1849a26d-8a77-45c2-a9d4-9dd57e96be94: 'Resource Downloads' # Resource Downloads
    3925f2c2-f707-4557-ae5e-1b4e36801755: 'Short Description' # Short Description
    8166c5cb-d63f-45c7-ae99-c33961a4cf3d: 'Facebook URL' # Facebook URL
    51614c49-f9f5-4660-abc0-d551062072b8: 'Message Series' # Message Series
    63998a0f-586b-4b03-ba27-74b694bf10dd: 'Hymn of the Month Music' # Hymn of the Month Music
    076138c8-eca9-475a-a69b-b912c2dae610: 'Stripe Payment Form' # Stripe Payment Form
    93012d1f-1633-417a-81d5-8f4b4e0ea023: Galleries # Galleries
    145582f2-5bbe-48b1-9f7b-9058b3759d1a: Audio # Audio
    302084e5-cc85-4e20-914e-49dd78f5e9a4: 'Call To Action' # Call To Action
    799005b5-502a-4951-bb7e-ae247d00979c: 'Hero Image' # Hero Image
    9541534e-7593-41ec-b0c8-5b12cecf235c: Body # Body
    67830663-1954-426b-8d89-89bcb764a68b: 'Background Image' # Background Image
    96489851-57e6-4cdd-9f3c-d2e785615f32: Heading # Heading
    a2bb0b6e-19a3-4fdd-9dfd-1761676fe2b8: 'Leadership Listing' # Leadership Listing
    a3adb82d-453d-4ae5-89d5-0f9b818b8d60: Messages # Messages
    a5663b9c-311e-405f-a780-b856c4cd8464: 'SEO Title' # SEO Title
    a9201e3f-ed7d-463f-b19f-20f487917a4a: Longitude # Longitude
    a71416ac-225c-4d76-acab-67dc94ad8809: 'Featured Sermon Series' # Featured Sermon Series
    abf9672d-3bab-4e78-a495-5f5b79756405: 'Default Hero Image' # Default Hero Image
    b149c792-7a23-44b8-b08b-12fd4059475d: 'Primary Image' # Primary Image
    b153d5f7-fd35-4731-9437-eb1333cdc3e2: 'SEO Description' # SEO Description
    b660e427-16f8-4219-ab16-4d955f0176b4: 'Small Heading' # Small Heading
    b5819ef5-9761-4d28-b9c2-d7c2a3b41532: 'Twitter Handle' # Twitter Handle
    b4204049-2a69-459e-b105-94be12ec6081: URL # URL
    ba477ad1-a81e-4f6c-9976-f0f2af90b390: 'Leadership Listing Details' # Leadership Listing Details
    c66e62d9-2ca8-4489-8c97-3f4dca8ccb60: Common # Common
    c67a7c62-3fbd-43ac-86c6-32c299b87bfe: Users # Users
    c9504fe8-d2fb-458b-a2e9-f8872585919a: 'Old Page Builder' # Old Page Builder
    cf5e0084-b552-41a9-acab-14266180cd09: 'Contact Form' # Contact Form
    d9d26b1f-c9ea-4482-8649-b8f387765fc8: 'Contact Form Details' # Contact Form Details
    d41c8997-be52-49d3-8b4b-a09ee99a12cd: 'Map Block' # Map Block
    de88a8f8-2563-459e-8a52-b3ad2f0ec006: 'News Categories' # News Categories
    df286b48-0507-4f99-9892-1f542903143c: Heading # Heading
    e2a3e24e-58ee-4326-8fc2-163003e8205b: 'Gallery Showcase Notes' # Gallery Showcase Notes
    e2b3f41d-b5fb-443c-988f-96c387bfa764: 'Number to Showcase' # Number to Showcase
    e91f5555-0d06-411a-a55c-c24f14632bf4: Pages # Pages
    e355e9ca-6733-4125-823c-1111afcb79eb: Options # Options
    e13796c0-a36c-490c-bf23-eb7f25d5465f: 'Hero Subheading' # Hero Subheading
    e7369087-a5e9-4f71-85ba-d13b9ef55293: 'Contact Form Recipients' # Contact Form Recipients
    ec8b995b-78c1-4e7e-a2ba-cab6d24be004: 'Leadership Position' # Leadership Position
    ee082c58-0248-40c1-be7f-ecbbd205f56e: 'Hero Heading' # Hero Heading
    ef3c7cfd-b16f-4a9a-b7f8-cad052fdbbef: 'Hymn/Psalm Name' # Hymn/Psalm Name
    efe1648a-3d7f-4a16-a249-8e6870078081: Body # Body
    f993b580-0e43-468a-9eab-ed72eef94d7a: 'Hymn of the Month Practice Tracks' # Hymn of the Month Practice Tracks
    fb27befa-4657-425c-b961-eeace2f94dc4: 'Block Background Image' # Block Background Image
    fb809945-7807-4e81-9c34-4ff030f0888a: Links # Links
    ff6f181e-01c5-4ca2-815d-5b737efab5d6: State # State
    ff7e24a0-727a-431d-94b0-8dcb29c49241: Page # Page
plugins:
  ckeditor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  craft-scheduler:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  enupal-stripe:
    edition: standard
    enabled: true
    licenseKey: FHWLA05QE7U9BTOH89XB1QZX
    schemaVersion: 3.2.1
    settings:
      adminNotificationRecipients: tj@buzzingpixel.com
      adminNotificationReplyToEmail: info@stmarkreformed.com
      adminNotificationSenderEmail: info@stmarkreformed.com
      adminNotificationSenderName: 'St. Mark Reformed'
      adminNotificationSubject: 'Payment Received: {{ order.number }} - {{ order.getPaymentForm().name }}'
      adminNotificationTemplate: null
      adminTemplateOverride: ''
      cancelAtPeriodEnd: ''
      capture: '1'
      chargeDescription: 'Order from {email}'
      chargeType: null
      currentUserEmail: ''
      customerNotificationReplyToEmail: ''
      customerNotificationSenderEmail: ''
      customerNotificationSenderName: ''
      customerNotificationSubject: ''
      customerNotificationTemplate: null
      customerTemplateOverride: ''
      defaultCurrency: USD
      displayTaxLabel: 0
      enableAdminNotification: '1'
      enableConnect: 0
      enableCustomerNotification: ''
      enableTaxes: 0
      enableVendorNotification: 0
      globalRate: 1
      liveClientId: null
      livePublishableKey: pk_test_51HjwSALCx654CZv1v8jVd72URBVSD7GkWowq0exDynZYlHfALylXCvhYdBv8kdFg9EYsN7LHVwEfv8j8V9asZtez003vH79xs8
      liveSecretKey: sk_test_51HjwSALCx654CZv1jewCZ1dkkyhoIDZocaelWxEm6FTVzfm61qn8DhK1erpc2DiwLLxgHrpv9ks3i4wu2h8sTWwd000ZPgjQ3U
      loadCss: '1'
      loadJquery: '1'
      oneTimeSetupFeeLabel: 'One time set-up fee'
      plansWithNickname: ''
      returnUrl: /building-fund/thank-you
      syncDefaultFormId: null
      syncDefaultStatusId: null
      syncEnabledDateRange: false
      syncEndDate: null
      syncIfUserExists: false
      syncLimit: 500
      syncStartDate: null
      syncType: 1
      tax: null
      taxType: 0
      testClientId: null
      testMode: 1
      testPublishableKey: pk_test_51HjwSALCx654CZv1v8jVd72URBVSD7GkWowq0exDynZYlHfALylXCvhYdBv8kdFg9EYsN7LHVwEfv8j8V9asZtez003vH79xs8
      testSecretKey: sk_test_51HjwSALCx654CZv1jewCZ1dkkyhoIDZocaelWxEm6FTVzfm61qn8DhK1erpc2DiwLLxgHrpv9ks3i4wu2h8sTWwd000ZPgjQ3U
      updateCustomerEmailOnStripe: ''
      useSca: '1'
      vendorNameFormat: null
      vendorNotificationReplyToEmail: null
      vendorNotificationSenderEmail: null
      vendorNotificationSenderName: null
      vendorNotificationSubject: null
      vendorNotificationTemplate: null
      vendorPaymentType: manually
      vendorSkipAdminReview: 0
      vendorTemplateOverride: null
      vendorUserFieldId: null
      vendorUserGroupId: null
  geoaddress:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.1
    settings:
      googleApiKey: AIzaSyDgRVyQkQ0T6k5dPlXCO_SLZOK4EGaBig0
  inventory:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redirect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.5
  slim-bridge:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'St. Mark Reformed Church'
  schemaVersion: 3.7.8
  timeZone: America/Chicago
