dateModified: 1611202298
email:
  fromEmail: info@stmarkreformed.com
  fromName: 'St. Mark Reformed Church'
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: tls
    host: smtp.mandrillapp.com
    password: $SMTP_PASSWORD
    port: '587'
    timeout: '30'
    useAuthentication: '1'
    username: info@buzzingpixel.com
  transportType: craft\mail\transportadapters\Smtp
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  ckeditor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  craft-static:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.0.0
    settings: null
  entry-instructions:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  enupal-stripe:
    edition: standard
    enabled: true
    licenseKey: FHWLA05QE7U9BTOH89XB1QZX
    schemaVersion: 3.0.0
    settings:
      adminNotificationRecipients: tj@buzzingpixel.com
      adminNotificationReplyToEmail: info@stmarkreformed.com
      adminNotificationSenderEmail: info@stmarkreformed.com
      adminNotificationSenderName: 'St. Mark Reformed'
      adminNotificationSubject: 'Payment Received: {{ order.number }} - {{ order.getPaymentForm().name }}'
      adminNotificationTemplate: null
      adminTemplateOverride: ''
      cancelAtPeriodEnd: ''
      capture: '1'
      chargeDescription: 'Order from {email}'
      chargeType: null
      currentUserEmail: ''
      customerNotificationReplyToEmail: ''
      customerNotificationSenderEmail: ''
      customerNotificationSenderName: ''
      customerNotificationSubject: ''
      customerNotificationTemplate: null
      customerTemplateOverride: ''
      defaultCurrency: USD
      displayTaxLabel: 0
      enableAdminNotification: '1'
      enableConnect: 0
      enableCustomerNotification: ''
      enableTaxes: 0
      enableVendorNotification: 0
      globalRate: 1
      liveClientId: null
      livePublishableKey: pk_test_51HjwSALCx654CZv1v8jVd72URBVSD7GkWowq0exDynZYlHfALylXCvhYdBv8kdFg9EYsN7LHVwEfv8j8V9asZtez003vH79xs8
      liveSecretKey: sk_test_51HjwSALCx654CZv1jewCZ1dkkyhoIDZocaelWxEm6FTVzfm61qn8DhK1erpc2DiwLLxgHrpv9ks3i4wu2h8sTWwd000ZPgjQ3U
      loadCss: '1'
      loadJquery: '1'
      oneTimeSetupFeeLabel: 'One time set-up fee'
      plansWithNickname: ''
      returnUrl: /building-fund/thank-you
      syncDefaultFormId: null
      syncDefaultStatusId: null
      syncEnabledDateRange: false
      syncEndDate: null
      syncIfUserExists: false
      syncLimit: 500
      syncStartDate: null
      syncType: 1
      tax: null
      taxType: 0
      testClientId: null
      testMode: 1
      testPublishableKey: pk_test_51HjwSALCx654CZv1v8jVd72URBVSD7GkWowq0exDynZYlHfALylXCvhYdBv8kdFg9EYsN7LHVwEfv8j8V9asZtez003vH79xs8
      testSecretKey: sk_test_51HjwSALCx654CZv1jewCZ1dkkyhoIDZocaelWxEm6FTVzfm61qn8DhK1erpc2DiwLLxgHrpv9ks3i4wu2h8sTWwd000ZPgjQ3U
      updateCustomerEmailOnStripe: ''
      useSca: '1'
      vendorNameFormat: null
      vendorNotificationReplyToEmail: null
      vendorNotificationSenderEmail: null
      vendorNotificationSenderName: null
      vendorNotificationSubject: null
      vendorNotificationTemplate: null
      vendorPaymentType: manually
      vendorSkipAdminReview: 0
      vendorTemplateOverride: null
      vendorUserFieldId: null
      vendorUserGroupId: null
  geoaddress:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.1
    settings:
      googleApiKey: AIzaSyDgRVyQkQ0T6k5dPlXCO_SLZOK4EGaBig0
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  inventory:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  minify:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redirect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.5
system:
  edition: pro
  live: true
  name: 'St. Mark Reformed Church'
  schemaVersion: 3.5.13
  timeZone: America/Chicago
