<?php

use App\Html\ButtonRows;
use App\Html\HtmlPath;
use BuzzingPixel\Templating\TemplateEngine;

assert($this instanceof TemplateEngine);
$pageTitle = $pageTitle ?? '';
$message = $message ?? null;
/** @var ButtonRows $buttonRows */
$buttonRows = $buttonRows ?? new ButtonRows();
?>

<h1 class="text-4xl font-semibold tracking-tight text-balance text-rx-light-blue-600">
    <?= $this->html($pageTitle) ?>
</h1>
<?php if ($message !== null): ?>
    <p class="mt-6 text-base font-medium text-pretty text-rx-gray-500">
        <?= $this->html($message) ?>
    </p>
<?php endif; ?>

<?=$this->partial(HtmlPath::BUTTON_ROWS, [
    'buttonRows' => $buttonRows,
])?>

