defaultPlacement: end
enableVersioning: true
handle: hymnsOfTheMonth
name: 'Hymns of the Month'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  94e92402-bc7d-4413-bc65-a236d81d53aa: # St. Mark Reformed Church
    enabledByDefault: true
    hasUrls: true
    template: _slimBridge/\App\Http\Response\Members\HymnsOfTheMonth\Single\SingleHymnOfTheMonthAction
    uriFormat: 'members/hymns-of-the-month/{slug}'
type: channel
