enableVersioning: '1'
handle: news
name: News
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  94e92402-bc7d-4413-bc65-a236d81d53aa: # St. Mark Reformed Church
    enabledByDefault: '1'
    hasUrls: '1'
    template: _controllerRoute/dev/news/entry
    uriFormat: 'news/{slug}'
type: channel
