defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  94e92402-bc7d-4413-bc65-a236d81d53aa: # St. Mark Reformed Church
    enabledByDefault: true
    hasUrls: true
    template: _slimBridge/\App\Http\Response\Pages\PageAction
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 6c6707aa-186c-4c95-a902-3ac42f9f72fb
type: structure
