enableVersioning: '1'
handle: pages
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  94e92402-bc7d-4413-bc65-a236d81d53aa:
    enabledByDefault: '1'
    hasUrls: '1'
    template: _controllerRoute/dev/pages/page
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 6c6707aa-186c-4c95-a902-3ac42f9f72fb
type: structure
