defaultPlacement: end
enableVersioning: true
handle: profiles
name: Profiles
propagationMethod: all
siteSettings:
  94e92402-bc7d-4413-bc65-a236d81d53aa: # St. Mark Reformed Church
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
