#!/usr/bin/env php
<?php

declare(strict_types=1);

use Config\BootCliConfigFactory;
use Config\BootConfigFactory;
use Config\Paths;
use RxAnte\AppBootstrap\Boot;

require __DIR__ . '/vendor/autoload.php';

new Boot()
    ->start(config: new BootConfigFactory()->create(true))
    ->buildContainer(register: Paths::DEPENDENCIES)
    ->registerEventSubscribers(register: Paths::EVENTS)
    ->buildCliApplication(new BootCliConfigFactory()->create())
    ->applyCommands()
    ->runApplication();
