name: Build images and deploy to production

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  IMAGE_NAMESPACE: ghcr.io/st-mark-reformed

jobs:
  build-api:
    name: Build api image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: docker/api/Dockerfile
          cache-from: type=registry,ref=ghcr.io/st-mark-reformed/stmarkreformed.com-api
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-api
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-api:${{ github.sha }}

  build-auth:
    name: Build auth image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: docker/auth/Dockerfile
          cache-from: type=registry,ref=ghcr.io/st-mark-reformed/stmarkreformed.com-auth
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-auth
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-auth:${{ github.sha }}

  build-app:
    name: Build app image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: docker/application/Dockerfile
          cache-from: type=registry,ref=ghcr.io/st-mark-reformed/stmarkreformed.com-app
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-app
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-app:${{ github.sha }}

  build-db:
    name: Build db image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: docker/db/Dockerfile
          cache-from: type=registry,ref=ghcr.io/st-mark-reformed/stmarkreformed.com-db
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-db
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-db:${{ github.sha }}

  build-proxy:
    name: Build proxy image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: docker/proxy/Dockerfile
          cache-from: type=registry,ref=ghcr.io/st-mark-reformed/stmarkreformed.com-proxy
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-proxy
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-proxy:${{ github.sha }}

  build-utility:
    name: Build utility image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: docker/utility/Dockerfile
          cache-from: type=registry,ref=ghcr.io/st-mark-reformed/stmarkreformed.com-utility
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-utility
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-utility:${{ github.sha }}

  build-web:
    name: Build web image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: docker/web/Dockerfile
          cache-from: type=registry,ref=ghcr.io/st-mark-reformed/stmarkreformed.com-web
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-web
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-web:${{ github.sha }}

  build-api-dependent-queue-consumer:
    name: Build api-queue-consumer image
    runs-on: ubuntu-latest
    needs: build-api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: docker/api-queue-consumer/Dockerfile
          build-args: |
            API_IMAGE=${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-api:${{ github.sha }}
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-api-queue-consumer
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-api-queue-consumer:${{ github.sha }}

  build-api-dependent-schedule-runner:
    name: Build api-schedule-runner image
    runs-on: ubuntu-latest
    needs: build-api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: docker/api-schedule-runner/Dockerfile
          build-args: |
            API_IMAGE=${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-api:${{ github.sha }}
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-api-schedule-runner
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-api-schedule-runner:${{ github.sha }}

  build-app-dependent-schedule-runner:
    name: Build app-schedule-runner image
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: docker/schedule-runner/Dockerfile
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            APP_IMAGE=${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-app:${{ github.sha }}
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-app-schedule-runner
            ${{ env.IMAGE_NAMESPACE }}/stmarkreformed.com-app-schedule-runner:${{ github.sha }}

  deploy:
    name: Deploy to production
    runs-on: self-hosted
    needs:
      - build-api
      - build-auth
      - build-app
      - build-db
      - build-proxy
      - build-utility
      - build-web
      - build-api-dependent-queue-consumer
      - build-api-dependent-schedule-runner
      - build-app-dependent-schedule-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy files to prod server
        uses: appleboy/scp-action@master
        with:
          username: ${{ vars.PROD_DEPLOY_SSH_USER }}
          host: ${{ vars.PROD_DEPLOY_SSH_HOST }}
          key: ${{ secrets.PROD_DEPLOY_SSH_PRIVATE_KEY }}
          source: "docker/application/.env, docker/proxy/.env, docker/web/.env, docker/api/.env, docker/auth/.env, docker/docker-compose.prod.yml"
          target: "/root/stmarkreformed.com"
      - name: Log in to prod server, pull images, and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ vars.PROD_DEPLOY_SSH_USER }}
          host: ${{ vars.PROD_DEPLOY_SSH_HOST }}
          key: ${{ secrets.PROD_DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd /root/stmarkreformed.com/docker;

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin;

            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-api;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-auth;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-api-queue-consumer;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-api-schedule-runner;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-app;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-db;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-proxy;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-app-schedule-runner;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-utility;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-web;

            cat /root/stmarkreformed.com/docker/api/.env.local >> /root/stmarkreformed.com/docker/api/.env;
            cat /root/stmarkreformed.com/docker/auth/.env.local >> /root/stmarkreformed.com/docker/auth/.env;
            cat /root/stmarkreformed.com/docker/application/.env.local >> /root/stmarkreformed.com/docker/application/.env;
            cat /root/stmarkreformed.com/docker/proxy/.env.local >> /root/stmarkreformed.com/docker/proxy/.env;
            cat /root/stmarkreformed.com/docker/web/.env.local >> /root/stmarkreformed.com/docker/web/.env;

            docker stack deploy \
              --compose-file docker-compose.prod.yml \
              --prune \
              --with-registry-auth \
              --resolve-image always \
              smrc;

            docker run -it --rm \
              --network smrc_default \
              --env-file ./api/.env \
              --entrypoint "" \
              --name smrc_api-migrations \
              ghcr.io/st-mark-reformed/stmarkreformed.com-api \
              bash -c "php cli migrate:up"

            docker run -it --rm \
              --network smrc_default \
              --env-file ./auth/.env \
              --entrypoint "" \
              --name smrc_auth-migrations \
              ghcr.io/st-mark-reformed/stmarkreformed.com-auth \
              bash -c "php cli migrate:up"
