name: Build images and deploy to production
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    name: Build images and push to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create buildx context
        run: docker buildx create --use
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build proxy image
        run: >
          docker buildx build
          --platform=linux/amd64
          --file docker/proxy/Dockerfile
          --cache-from ghcr.io/st-mark-reformed/stmarkreformed.com-proxy
          --build-arg BUILDKIT_INLINE_CACHE=1
          --tag ghcr.io/st-mark-reformed/stmarkreformed.com-proxy
          --tag ghcr.io/st-mark-reformed/stmarkreformed.com-proxy:"$GITHUB_SHA"
          --push
          .
      - name: Build web image
        run: >
          docker buildx build
          --platform=linux/amd64
          --file docker/web/Dockerfile
          --cache-from ghcr.io/st-mark-reformed/stmarkreformed.com-web
          --build-arg BUILDKIT_INLINE_CACHE=1
          --tag ghcr.io/st-mark-reformed/stmarkreformed.com-web
          --tag ghcr.io/st-mark-reformed/stmarkreformed.com-web:"$GITHUB_SHA"
          --push
          .
      - name: Build app image
        run: >
          docker buildx build
          --platform=linux/amd64
          --file docker/application/Dockerfile
          --cache-from ghcr.io/st-mark-reformed/stmarkreformed.com-app
          --build-arg BUILDKIT_INLINE_CACHE=1
          --tag ghcr.io/st-mark-reformed/stmarkreformed.com-app
          --tag ghcr.io/st-mark-reformed/stmarkreformed.com-app:"$GITHUB_SHA"
          --push
          .
      - name: Build schedule-runner image
        run: >
          docker buildx build
          --platform=linux/amd64
          --file docker/schedule-runner/Dockerfile
          --build-arg BUILDKIT_INLINE_CACHE=1
          --build-arg APP_IMAGE=ghcr.io/st-mark-reformed/stmarkreformed.com-app:"$GITHUB_SHA"
          --tag ghcr.io/st-mark-reformed/stmarkreformed.com-app-schedule-runner
          --tag ghcr.io/st-mark-reformed/stmarkreformed.com-app-schedule-runner:"$GITHUB_SHA"
          --push
          .
      - name: Build db image
        run: >
          docker buildx build
          --platform=linux/amd64
          --file docker/db/Dockerfile
          --cache-from ghcr.io/st-mark-reformed/stmarkreformed.com-db
          --build-arg BUILDKIT_INLINE_CACHE=1
          --tag ghcr.io/st-mark-reformed/stmarkreformed.com-db
          --tag ghcr.io/st-mark-reformed/stmarkreformed.com-db:"$GITHUB_SHA"
          --push
          .
      - name: Build utility image
        run: >
          docker buildx build
          --platform=linux/amd64
          --file docker/utility/Dockerfile
          --cache-from ghcr.io/st-mark-reformed/stmarkreformed.com-utility
          --build-arg BUILDKIT_INLINE_CACHE=1
          --tag ghcr.io/st-mark-reformed/stmarkreformed.com-utility
          --tag ghcr.io/st-mark-reformed/stmarkreformed.com-utility:"$GITHUB_SHA"
          --push
          .
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy files to prod server
        uses: appleboy/scp-action@master
        with:
          username: ${{ vars.PROD_DEPLOY_SSH_USER }}
          host: ${{ vars.PROD_DEPLOY_SSH_HOST }}
          key: ${{ secrets.PROD_DEPLOY_SSH_PRIVATE_KEY }}
          source: "docker/application/.env, docker/proxy/.env, docker/web/.env, docker/docker-compose.prod.yml"
          target: "/root/stmarkreformed.com"
      - name: Log in to prod server, pull images, and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ vars.PROD_DEPLOY_SSH_USER }}
          host: ${{ vars.PROD_DEPLOY_SSH_HOST }}
          key: ${{ secrets.PROD_DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            cd /root/stmarkreformed.com/docker;

            # Log in to github docker registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin;

            # Pull Images
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-proxy;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-web;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-app;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-app-schedule-runner;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-db;
            docker pull ghcr.io/st-mark-reformed/stmarkreformed.com-utility;

            # Docker can be weird about .env, make sure local is concat into .env
            cat /root/stmarkreformed.com/docker/proxy/.env.local >> /root/stmarkreformed.com/docker/proxy/.env;
            cat /root/stmarkreformed.com/docker/web/.env.local >> /root/stmarkreformed.com/docker/web/.env;
            cat /root/stmarkreformed.com/docker/application/.env.local >> /root/stmarkreformed.com/docker/application/.env;

            # Deploy new images
            docker stack deploy \
              --compose-file docker-compose.prod.yml \
              --prune \
              --with-registry-auth \
              --resolve-image always \
              smrc;
