name: CI
on: [push]
jobs:
  code-quality:
    runs-on: self-hosted
    steps:
      # TODO: add code quality tools
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build Docker image
        run: ./dev docker-build
  trigger-deploy:
    needs: code-quality
    runs-on: self-hosted
    if: contains(github.ref, 'update-docker-config')
    steps:
      - name: Trigger deploy script
        run: /Volumes/Matrix/github-actions-runners/stmarkreformed.com-actions-runner/trigger-prod-deployment.sh
